unity2ros:
  ros__parameters:
    ROS_IP: "127.0.0.1"

planner:
  ros__parameters:
    default_video_directory: "/home/ros/recordings"

rosbridge:
  ros__parameters:
    somethingelse: "Hello"