planner:
  ros__parameters:
    rate: 3
    autodepth: 
      kp: 0.4
      ki: 0.8
      kd: 0.1
      min_depth: -0.3
      max_depth: -1.0

camera:
  ros__parameters:
    width: 640
    height: 480
    frame_rate: 30

recorder:
  ros__parameters:
    width: 640
    height: 480
    frame_rate: 30
    video_dir: "/home/ros/recordings"

localiser:
  ros__parameters:
    rate: 10
    map_dir: "/home/ros/maps"

hardware:
  ros__parameters:
    show_ip: true