unity2ros:
  ros__parameters:
    ROS_IP: "0.0.0.0"

planner:
  ros__parameters:
    rate: 10

camera:
  ros__parameters:
    width: 640
    height: 480
    frame_rate: 30

recorder:
  ros__parameters:
    width: 640
    height: 480
    frame_rate: 30
    video_dir: "/home/ros/recordings"

localiser:
  ros__parameters:
    rate: 10

rosbridge:
  ros__parameters:
    somethingelse: "Hello"